/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReviewIndexRouteImport } from './routes/review.index'
import { Route as ReviewSummaryRouteImport } from './routes/review.summary'
import { Route as ReviewRisksRouteImport } from './routes/review.risks'
import { Route as ReviewObligationsRouteImport } from './routes/review.obligations'
import { Route as ReviewHumanReviewRouteImport } from './routes/review.human-review'
import { Route as ReviewExtractedRouteImport } from './routes/review.extracted'
import { Route as ReviewClausesRouteImport } from './routes/review.clauses'
import { Route as ReviewAuditTrailRouteImport } from './routes/review.audit-trail'

const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewIndexRoute = ReviewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReviewRoute,
} as any)
const ReviewSummaryRoute = ReviewSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => ReviewRoute,
} as any)
const ReviewRisksRoute = ReviewRisksRouteImport.update({
  id: '/risks',
  path: '/risks',
  getParentRoute: () => ReviewRoute,
} as any)
const ReviewObligationsRoute = ReviewObligationsRouteImport.update({
  id: '/obligations',
  path: '/obligations',
  getParentRoute: () => ReviewRoute,
} as any)
const ReviewHumanReviewRoute = ReviewHumanReviewRouteImport.update({
  id: '/human-review',
  path: '/human-review',
  getParentRoute: () => ReviewRoute,
} as any)
const ReviewExtractedRoute = ReviewExtractedRouteImport.update({
  id: '/extracted',
  path: '/extracted',
  getParentRoute: () => ReviewRoute,
} as any)
const ReviewClausesRoute = ReviewClausesRouteImport.update({
  id: '/clauses',
  path: '/clauses',
  getParentRoute: () => ReviewRoute,
} as any)
const ReviewAuditTrailRoute = ReviewAuditTrailRouteImport.update({
  id: '/audit-trail',
  path: '/audit-trail',
  getParentRoute: () => ReviewRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/review': typeof ReviewRouteWithChildren
  '/review/audit-trail': typeof ReviewAuditTrailRoute
  '/review/clauses': typeof ReviewClausesRoute
  '/review/extracted': typeof ReviewExtractedRoute
  '/review/human-review': typeof ReviewHumanReviewRoute
  '/review/obligations': typeof ReviewObligationsRoute
  '/review/risks': typeof ReviewRisksRoute
  '/review/summary': typeof ReviewSummaryRoute
  '/review/': typeof ReviewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/review/audit-trail': typeof ReviewAuditTrailRoute
  '/review/clauses': typeof ReviewClausesRoute
  '/review/extracted': typeof ReviewExtractedRoute
  '/review/human-review': typeof ReviewHumanReviewRoute
  '/review/obligations': typeof ReviewObligationsRoute
  '/review/risks': typeof ReviewRisksRoute
  '/review/summary': typeof ReviewSummaryRoute
  '/review': typeof ReviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/review': typeof ReviewRouteWithChildren
  '/review/audit-trail': typeof ReviewAuditTrailRoute
  '/review/clauses': typeof ReviewClausesRoute
  '/review/extracted': typeof ReviewExtractedRoute
  '/review/human-review': typeof ReviewHumanReviewRoute
  '/review/obligations': typeof ReviewObligationsRoute
  '/review/risks': typeof ReviewRisksRoute
  '/review/summary': typeof ReviewSummaryRoute
  '/review/': typeof ReviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/review'
    | '/review/audit-trail'
    | '/review/clauses'
    | '/review/extracted'
    | '/review/human-review'
    | '/review/obligations'
    | '/review/risks'
    | '/review/summary'
    | '/review/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/review/audit-trail'
    | '/review/clauses'
    | '/review/extracted'
    | '/review/human-review'
    | '/review/obligations'
    | '/review/risks'
    | '/review/summary'
    | '/review'
  id:
    | '__root__'
    | '/'
    | '/review'
    | '/review/audit-trail'
    | '/review/clauses'
    | '/review/extracted'
    | '/review/human-review'
    | '/review/obligations'
    | '/review/risks'
    | '/review/summary'
    | '/review/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReviewRoute: typeof ReviewRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review/': {
      id: '/review/'
      path: '/'
      fullPath: '/review/'
      preLoaderRoute: typeof ReviewIndexRouteImport
      parentRoute: typeof ReviewRoute
    }
    '/review/summary': {
      id: '/review/summary'
      path: '/summary'
      fullPath: '/review/summary'
      preLoaderRoute: typeof ReviewSummaryRouteImport
      parentRoute: typeof ReviewRoute
    }
    '/review/risks': {
      id: '/review/risks'
      path: '/risks'
      fullPath: '/review/risks'
      preLoaderRoute: typeof ReviewRisksRouteImport
      parentRoute: typeof ReviewRoute
    }
    '/review/obligations': {
      id: '/review/obligations'
      path: '/obligations'
      fullPath: '/review/obligations'
      preLoaderRoute: typeof ReviewObligationsRouteImport
      parentRoute: typeof ReviewRoute
    }
    '/review/human-review': {
      id: '/review/human-review'
      path: '/human-review'
      fullPath: '/review/human-review'
      preLoaderRoute: typeof ReviewHumanReviewRouteImport
      parentRoute: typeof ReviewRoute
    }
    '/review/extracted': {
      id: '/review/extracted'
      path: '/extracted'
      fullPath: '/review/extracted'
      preLoaderRoute: typeof ReviewExtractedRouteImport
      parentRoute: typeof ReviewRoute
    }
    '/review/clauses': {
      id: '/review/clauses'
      path: '/clauses'
      fullPath: '/review/clauses'
      preLoaderRoute: typeof ReviewClausesRouteImport
      parentRoute: typeof ReviewRoute
    }
    '/review/audit-trail': {
      id: '/review/audit-trail'
      path: '/audit-trail'
      fullPath: '/review/audit-trail'
      preLoaderRoute: typeof ReviewAuditTrailRouteImport
      parentRoute: typeof ReviewRoute
    }
  }
}

interface ReviewRouteChildren {
  ReviewAuditTrailRoute: typeof ReviewAuditTrailRoute
  ReviewClausesRoute: typeof ReviewClausesRoute
  ReviewExtractedRoute: typeof ReviewExtractedRoute
  ReviewHumanReviewRoute: typeof ReviewHumanReviewRoute
  ReviewObligationsRoute: typeof ReviewObligationsRoute
  ReviewRisksRoute: typeof ReviewRisksRoute
  ReviewSummaryRoute: typeof ReviewSummaryRoute
  ReviewIndexRoute: typeof ReviewIndexRoute
}

const ReviewRouteChildren: ReviewRouteChildren = {
  ReviewAuditTrailRoute: ReviewAuditTrailRoute,
  ReviewClausesRoute: ReviewClausesRoute,
  ReviewExtractedRoute: ReviewExtractedRoute,
  ReviewHumanReviewRoute: ReviewHumanReviewRoute,
  ReviewObligationsRoute: ReviewObligationsRoute,
  ReviewRisksRoute: ReviewRisksRoute,
  ReviewSummaryRoute: ReviewSummaryRoute,
  ReviewIndexRoute: ReviewIndexRoute,
}

const ReviewRouteWithChildren =
  ReviewRoute._addFileChildren(ReviewRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReviewRoute: ReviewRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
